# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: herokuFastAPI_wf

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: DVC
      uses: iterative/setup-dvc@v1
    - name: Pull data from DVC
      run: dvc pull data -R
    - name: Run Flake8
      run: flake8
    - name: Run pytest
      run: pytest
